name: Node CI

on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.16.x
      uses: actions/setup-node@v1
      with:
        version: 10.16.x
    - name: Install dependencies
      run: |
        yarn install
    - name: Crypress tests
      run: |
        yarn cypress:run
